apiVersion: v1
kind: Pod
spec:
  containers:
  - name: jnlp
    image: jenkinsci/jnlp-slave:3.29-1-alpine
    volumeMounts:
    - name: dockersock
      mountPath: /var/run/docker.sock
  - name: docker
    image: docker:latest
    command:
    - cat
    volumeMounts:
    - name: dockersock
      mountPath: /var/run/docker.sock
  volumes:
  - name: dockersock
    hostPath:
      path: /var/run/docker.sock